apiVersion: v1
kind: Service
metadata:
  name: acfitness-app-green-service
spec:
  selector:
    app: acfitness-app
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
