apiVersion: apps/v1
kind: Deployment
metadata:
  name: acfitness-app-rollingupdate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acfitness-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: acfitness-app
    spec:
      containers:
        - name: acfitness-app
          image: fitness-app:latest
          imagePullPolicy: Never
          # image: your_dockerhub_username/acfitness-app:${IMAGE_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
