apiVersion: v1
kind: Service
metadata:
  name: acfitness-app-shadow-service
spec:
  selector:
    app: acfitness-app
    version: shadow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
