apiVersion: apps/v1
kind: Deployment
metadata:
  name: acfitness-app-shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acfitness-app
      version: shadow
  template:
    metadata:
      labels:
        app: acfitness-app
        version: shadow
    spec:
      containers:
        - name: acfitness-app
          image: fitness-app:latest
          imagePullPolicy: Never
          # image: your_dockerhub_username/acfitness-app:${IMAGE_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
