apiVersion: apps/v1
kind: Deployment
metadata:
  name: acfitness-app
  labels:
    app: acfitness-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acfitness-app
  template:
    metadata:
      labels:
        app: acfitness-app
    spec:
      containers:
        - name: acfitness-app
          image: your_dockerhub_username/acfitness-app:${IMAGE_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
