apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-fitness-app
  labels:
    app: flask-fitness-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-fitness-app
  template:
    metadata:
      labels:
        app: flask-fitness-app
    spec:
      containers:
        - name: flask-fitness-app
          image: your_dockerhub_username/flask-fitness-app:${IMAGE_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
